services:
  postgres:
    image: postgres:17-alpine
    container_name: lea21-postgres
    restart: unless-stopped
    ports:
      - '54852:5432'
    environment:
      POSTGRES_DB: lea21
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d lea21']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
