/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  text,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', ['uk', 'en'])
export const enum_form_submissions_status = pgEnum('enum_form_submissions_status', [
  'new',
  'in-progress',
  'resolved',
])
export const enum_landing_page_expertise_stats_align = pgEnum(
  'enum_landing_page_expertise_stats_align',
  ['start', 'end'],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    seedKey: varchar('seed_key'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    uniqueIndex('media_seed_key_idx').on(columns.seedKey),
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const media_locales = pgTable(
  'media_locales',
  {
    alt: varchar('alt').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('media_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [media.id],
      name: 'media_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const form_submissions = pgTable(
  'form_submissions',
  {
    id: serial('id').primaryKey(),
    firstName: varchar('first_name').notNull(),
    lastName: varchar('last_name').notNull(),
    email: varchar('email').notNull(),
    phone: varchar('phone').notNull(),
    message: varchar('message').notNull(),
    status: enum_form_submissions_status('status').default('new'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('form_submissions_updated_at_idx').on(columns.updatedAt),
    index('form_submissions_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    'form-submissionsID': integer('form_submissions_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_form_submissions_id_idx').on(
      columns['form-submissionsID'],
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['form-submissionsID']],
      foreignColumns: [form_submissions.id],
      name: 'payload_locked_documents_rels_form_submissions_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const landing_page_header_nav_items = pgTable(
  'landing_page_header_nav_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    href: varchar('href').notNull(),
  },
  (columns) => [
    index('landing_page_header_nav_items_order_idx').on(columns._order),
    index('landing_page_header_nav_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_header_nav_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_header_nav_items_locales = pgTable(
  'landing_page_header_nav_items_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_header_nav_items_locales_locale_parent_id_uniqu').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_header_nav_items.id],
      name: 'landing_page_header_nav_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_for_who_primary_items = pgTable(
  'landing_page_for_who_primary_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    icon: integer('icon_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('landing_page_for_who_primary_items_order_idx').on(columns._order),
    index('landing_page_for_who_primary_items_parent_id_idx').on(columns._parentID),
    index('landing_page_for_who_primary_items_icon_idx').on(columns.icon),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_for_who_primary_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_for_who_primary_items_locales = pgTable(
  'landing_page_for_who_primary_items_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_for_who_primary_items_locales_locale_parent_id_').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_for_who_primary_items.id],
      name: 'landing_page_for_who_primary_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_for_who_secondary_items = pgTable(
  'landing_page_for_who_secondary_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    icon: integer('icon_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('landing_page_for_who_secondary_items_order_idx').on(columns._order),
    index('landing_page_for_who_secondary_items_parent_id_idx').on(columns._parentID),
    index('landing_page_for_who_secondary_items_icon_idx').on(columns.icon),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_for_who_secondary_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_for_who_secondary_items_locales = pgTable(
  'landing_page_for_who_secondary_items_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_for_who_secondary_items_locales_locale_parent_i').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_for_who_secondary_items.id],
      name: 'landing_page_for_who_secondary_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_results_items = pgTable(
  'landing_page_results_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('landing_page_results_items_order_idx').on(columns._order),
    index('landing_page_results_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_results_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_results_items_locales = pgTable(
  'landing_page_results_items_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_results_items_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_results_items.id],
      name: 'landing_page_results_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_process_steps = pgTable(
  'landing_page_process_steps',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    raised: boolean('raised'),
  },
  (columns) => [
    index('landing_page_process_steps_order_idx').on(columns._order),
    index('landing_page_process_steps_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_process_steps_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_process_steps_locales = pgTable(
  'landing_page_process_steps_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_process_steps_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_process_steps.id],
      name: 'landing_page_process_steps_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_program_modules = pgTable(
  'landing_page_program_modules',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
  },
  (columns) => [
    index('landing_page_program_modules_order_idx').on(columns._order),
    index('landing_page_program_modules_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_program_modules_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_program_modules_locales = pgTable(
  'landing_page_program_modules_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_program_modules_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_program_modules.id],
      name: 'landing_page_program_modules_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_expertise_stats = pgTable(
  'landing_page_expertise_stats',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    align: enum_landing_page_expertise_stats_align('align').notNull(),
  },
  (columns) => [
    index('landing_page_expertise_stats_order_idx').on(columns._order),
    index('landing_page_expertise_stats_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_expertise_stats_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_expertise_stats_locales = pgTable(
  'landing_page_expertise_stats_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_expertise_stats_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_expertise_stats.id],
      name: 'landing_page_expertise_stats_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_certificates_items = pgTable(
  'landing_page_certificates_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('landing_page_certificates_items_order_idx').on(columns._order),
    index('landing_page_certificates_items_parent_id_idx').on(columns._parentID),
    index('landing_page_certificates_items_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_certificates_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_certificates_items_locales = pgTable(
  'landing_page_certificates_items_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_certificates_items_locales_locale_parent_id_uni').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_certificates_items.id],
      name: 'landing_page_certificates_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_blocks_video_review = pgTable(
  'landing_page_blocks_video_review',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    video: integer('video_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    avatar: integer('avatar_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    instagramUrl: varchar('instagram_url'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('landing_page_blocks_video_review_order_idx').on(columns._order),
    index('landing_page_blocks_video_review_parent_id_idx').on(columns._parentID),
    index('landing_page_blocks_video_review_path_idx').on(columns._path),
    index('landing_page_blocks_video_review_video_idx').on(columns.video),
    index('landing_page_blocks_video_review_image_idx').on(columns.image),
    index('landing_page_blocks_video_review_avatar_idx').on(columns.avatar),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_blocks_video_review_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_blocks_video_review_locales = pgTable(
  'landing_page_blocks_video_review_locales',
  {
    name: varchar('name').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_blocks_video_review_locales_locale_parent_id_un').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_blocks_video_review.id],
      name: 'landing_page_blocks_video_review_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_blocks_text_review = pgTable(
  'landing_page_blocks_text_review',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    avatar: integer('avatar_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    instagramUrl: varchar('instagram_url'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('landing_page_blocks_text_review_order_idx').on(columns._order),
    index('landing_page_blocks_text_review_parent_id_idx').on(columns._parentID),
    index('landing_page_blocks_text_review_path_idx').on(columns._path),
    index('landing_page_blocks_text_review_avatar_idx').on(columns.avatar),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_blocks_text_review_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_blocks_text_review_locales = pgTable(
  'landing_page_blocks_text_review_locales',
  {
    text: varchar('text').notNull(),
    name: varchar('name').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_blocks_text_review_locales_locale_parent_id_uni').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_blocks_text_review.id],
      name: 'landing_page_blocks_text_review_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_reviews_video_items = pgTable(
  'landing_page_reviews_video_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    avatar: integer('avatar_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    instagramUrl: varchar('instagram_url'),
  },
  (columns) => [
    index('landing_page_reviews_video_items_order_idx').on(columns._order),
    index('landing_page_reviews_video_items_parent_id_idx').on(columns._parentID),
    index('landing_page_reviews_video_items_image_idx').on(columns.image),
    index('landing_page_reviews_video_items_avatar_idx').on(columns.avatar),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_reviews_video_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_reviews_video_items_locales = pgTable(
  'landing_page_reviews_video_items_locales',
  {
    name: varchar('name').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_reviews_video_items_locales_locale_parent_id_un').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_reviews_video_items.id],
      name: 'landing_page_reviews_video_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_reviews_text_items = pgTable(
  'landing_page_reviews_text_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    avatar: integer('avatar_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    instagramUrl: varchar('instagram_url'),
  },
  (columns) => [
    index('landing_page_reviews_text_items_order_idx').on(columns._order),
    index('landing_page_reviews_text_items_parent_id_idx').on(columns._parentID),
    index('landing_page_reviews_text_items_avatar_idx').on(columns.avatar),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_reviews_text_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_reviews_text_items_locales = pgTable(
  'landing_page_reviews_text_items_locales',
  {
    text: varchar('text').notNull(),
    name: varchar('name').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_reviews_text_items_locales_locale_parent_id_uni').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_reviews_text_items.id],
      name: 'landing_page_reviews_text_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_footer_left_links = pgTable(
  'landing_page_footer_left_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    href: varchar('href').notNull(),
  },
  (columns) => [
    index('landing_page_footer_left_links_order_idx').on(columns._order),
    index('landing_page_footer_left_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_footer_left_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_footer_left_links_locales = pgTable(
  'landing_page_footer_left_links_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_footer_left_links_locales_locale_parent_id_uniq').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_footer_left_links.id],
      name: 'landing_page_footer_left_links_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_footer_right_links = pgTable(
  'landing_page_footer_right_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    href: varchar('href').notNull(),
  },
  (columns) => [
    index('landing_page_footer_right_links_order_idx').on(columns._order),
    index('landing_page_footer_right_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_footer_right_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_footer_right_links_locales = pgTable(
  'landing_page_footer_right_links_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_footer_right_links_locales_locale_parent_id_uni').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_footer_right_links.id],
      name: 'landing_page_footer_right_links_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_footer_social_links = pgTable(
  'landing_page_footer_social_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    url: varchar('url').notNull(),
  },
  (columns) => [
    index('landing_page_footer_social_links_order_idx').on(columns._order),
    index('landing_page_footer_social_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_footer_social_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page_footer_social_links_locales = pgTable(
  'landing_page_footer_social_links_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_footer_social_links_locales_locale_parent_id_un').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page_footer_social_links.id],
      name: 'landing_page_footer_social_links_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const landing_page = pgTable(
  'landing_page',
  {
    id: serial('id').primaryKey(),
    hero_backgroundImage: integer('hero_background_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    hero_figureImage: integer('hero_figure_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    project_ctaHref: varchar('project_cta_href').notNull(),
    project_image: integer('project_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    results_backgroundImage: integer('results_background_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    results_image: integer('results_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    expertise_image: integer('expertise_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    cta_buttonHref: varchar('cta_button_href').notNull(),
    cta_backgroundImage: integer('cta_background_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    contact_image: integer('contact_image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    footer_contact_href: varchar('footer_contact_href').notNull(),
    footer_write_href: varchar('footer_write_href').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('landing_page_hero_hero_background_image_idx').on(columns.hero_backgroundImage),
    index('landing_page_hero_hero_figure_image_idx').on(columns.hero_figureImage),
    index('landing_page_project_project_image_idx').on(columns.project_image),
    index('landing_page_results_results_background_image_idx').on(columns.results_backgroundImage),
    index('landing_page_results_results_image_idx').on(columns.results_image),
    index('landing_page_expertise_expertise_image_idx').on(columns.expertise_image),
    index('landing_page_cta_cta_background_image_idx').on(columns.cta_backgroundImage),
    index('landing_page_contact_contact_image_idx').on(columns.contact_image),
  ],
)

export const landing_page_locales = pgTable(
  'landing_page_locales',
  {
    seo_metaTitle: varchar('seo_meta_title').notNull(),
    seo_metaDescription: varchar('seo_meta_description').notNull(),
    header_logoText: varchar('header_logo_text').notNull(),
    header_ctaLabel: varchar('header_cta_label').notNull(),
    hero_titleLineOne: varchar('hero_title_line_one').notNull(),
    hero_titleLineTwo: varchar('hero_title_line_two').notNull(),
    hero_script: varchar('hero_script').notNull(),
    hero_subtitle: varchar('hero_subtitle').notNull(),
    hero_description: varchar('hero_description').notNull(),
    hero_desktopDescription: varchar('hero_desktop_description').notNull(),
    hero_availability: varchar('hero_availability').notNull(),
    hero_durationValue: varchar('hero_duration_value').notNull(),
    hero_durationLabel: varchar('hero_duration_label').notNull(),
    project_title: varchar('project_title').notNull(),
    project_scriptTitle: varchar('project_script_title').notNull(),
    project_intro: varchar('project_intro').notNull(),
    project_body: varchar('project_body').notNull(),
    project_ctaLabel: varchar('project_cta_label').notNull(),
    forWho_title: varchar('for_who_title').notNull(),
    forWho_scriptTitle: varchar('for_who_script_title').notNull(),
    results_title: varchar('results_title').notNull(),
    results_summary: varchar('results_summary').notNull(),
    process_title: varchar('process_title').notNull(),
    process_scriptTitle: varchar('process_script_title').notNull(),
    program_title: varchar('program_title').notNull(),
    expertise_title: varchar('expertise_title').notNull(),
    expertise_scriptTitle: varchar('expertise_script_title').notNull(),
    expertise_description: varchar('expertise_description').notNull(),
    expertise_intro: varchar('expertise_intro').notNull(),
    certificates_title: varchar('certificates_title').notNull(),
    certificates_scriptWordOne: varchar('certificates_script_word_one').notNull(),
    certificates_scriptWordTwo: varchar('certificates_script_word_two').notNull(),
    reviews_title: varchar('reviews_title').notNull(),
    reviews_scriptTitle: varchar('reviews_script_title').notNull(),
    cta_title: varchar('cta_title').notNull(),
    cta_description: varchar('cta_description').notNull(),
    cta_buttonLabel: varchar('cta_button_label').notNull(),
    contact_eyebrow: varchar('contact_eyebrow').notNull(),
    contact_title: varchar('contact_title').notNull(),
    contact_script: varchar('contact_script').notNull(),
    contact_placeholders_firstName: varchar('contact_placeholders_first_name').notNull(),
    contact_placeholders_lastName: varchar('contact_placeholders_last_name').notNull(),
    contact_placeholders_email: varchar('contact_placeholders_email').notNull(),
    contact_placeholders_phone: varchar('contact_placeholders_phone').notNull(),
    contact_placeholders_message: varchar('contact_placeholders_message').notNull(),
    contact_submitLabel: varchar('contact_submit_label').notNull(),
    contact_successMessage: varchar('contact_success_message').notNull(),
    contact_errorMessage: varchar('contact_error_message').notNull(),
    footer_logoText: varchar('footer_logo_text').notNull(),
    footer_contact_title: varchar('footer_contact_title').notNull(),
    footer_contact_label: varchar('footer_contact_label').notNull(),
    footer_write_title: varchar('footer_write_title').notNull(),
    footer_write_label: varchar('footer_write_label').notNull(),
    footer_socialsTitle: varchar('footer_socials_title').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('landing_page_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [landing_page.id],
      name: 'landing_page_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media_locales = relations(media_locales, ({ one }) => ({
  _parentID: one(media, {
    fields: [media_locales._parentID],
    references: [media.id],
    relationName: '_locales',
  }),
}))
export const relations_media = relations(media, ({ many }) => ({
  _locales: many(media_locales, {
    relationName: '_locales',
  }),
}))
export const relations_form_submissions = relations(form_submissions, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    'form-submissionsID': one(form_submissions, {
      fields: [payload_locked_documents_rels['form-submissionsID']],
      references: [form_submissions.id],
      relationName: 'form-submissions',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_landing_page_header_nav_items_locales = relations(
  landing_page_header_nav_items_locales,
  ({ one }) => ({
    _parentID: one(landing_page_header_nav_items, {
      fields: [landing_page_header_nav_items_locales._parentID],
      references: [landing_page_header_nav_items.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_header_nav_items = relations(
  landing_page_header_nav_items,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_header_nav_items._parentID],
      references: [landing_page.id],
      relationName: 'header_navItems',
    }),
    _locales: many(landing_page_header_nav_items_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_for_who_primary_items_locales = relations(
  landing_page_for_who_primary_items_locales,
  ({ one }) => ({
    _parentID: one(landing_page_for_who_primary_items, {
      fields: [landing_page_for_who_primary_items_locales._parentID],
      references: [landing_page_for_who_primary_items.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_for_who_primary_items = relations(
  landing_page_for_who_primary_items,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_for_who_primary_items._parentID],
      references: [landing_page.id],
      relationName: 'forWho_primaryItems',
    }),
    _locales: many(landing_page_for_who_primary_items_locales, {
      relationName: '_locales',
    }),
    icon: one(media, {
      fields: [landing_page_for_who_primary_items.icon],
      references: [media.id],
      relationName: 'icon',
    }),
  }),
)
export const relations_landing_page_for_who_secondary_items_locales = relations(
  landing_page_for_who_secondary_items_locales,
  ({ one }) => ({
    _parentID: one(landing_page_for_who_secondary_items, {
      fields: [landing_page_for_who_secondary_items_locales._parentID],
      references: [landing_page_for_who_secondary_items.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_for_who_secondary_items = relations(
  landing_page_for_who_secondary_items,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_for_who_secondary_items._parentID],
      references: [landing_page.id],
      relationName: 'forWho_secondaryItems',
    }),
    _locales: many(landing_page_for_who_secondary_items_locales, {
      relationName: '_locales',
    }),
    icon: one(media, {
      fields: [landing_page_for_who_secondary_items.icon],
      references: [media.id],
      relationName: 'icon',
    }),
  }),
)
export const relations_landing_page_results_items_locales = relations(
  landing_page_results_items_locales,
  ({ one }) => ({
    _parentID: one(landing_page_results_items, {
      fields: [landing_page_results_items_locales._parentID],
      references: [landing_page_results_items.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_results_items = relations(
  landing_page_results_items,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_results_items._parentID],
      references: [landing_page.id],
      relationName: 'results_items',
    }),
    _locales: many(landing_page_results_items_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_process_steps_locales = relations(
  landing_page_process_steps_locales,
  ({ one }) => ({
    _parentID: one(landing_page_process_steps, {
      fields: [landing_page_process_steps_locales._parentID],
      references: [landing_page_process_steps.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_process_steps = relations(
  landing_page_process_steps,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_process_steps._parentID],
      references: [landing_page.id],
      relationName: 'process_steps',
    }),
    _locales: many(landing_page_process_steps_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_program_modules_locales = relations(
  landing_page_program_modules_locales,
  ({ one }) => ({
    _parentID: one(landing_page_program_modules, {
      fields: [landing_page_program_modules_locales._parentID],
      references: [landing_page_program_modules.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_program_modules = relations(
  landing_page_program_modules,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_program_modules._parentID],
      references: [landing_page.id],
      relationName: 'program_modules',
    }),
    _locales: many(landing_page_program_modules_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_expertise_stats_locales = relations(
  landing_page_expertise_stats_locales,
  ({ one }) => ({
    _parentID: one(landing_page_expertise_stats, {
      fields: [landing_page_expertise_stats_locales._parentID],
      references: [landing_page_expertise_stats.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_expertise_stats = relations(
  landing_page_expertise_stats,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_expertise_stats._parentID],
      references: [landing_page.id],
      relationName: 'expertise_stats',
    }),
    _locales: many(landing_page_expertise_stats_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_certificates_items_locales = relations(
  landing_page_certificates_items_locales,
  ({ one }) => ({
    _parentID: one(landing_page_certificates_items, {
      fields: [landing_page_certificates_items_locales._parentID],
      references: [landing_page_certificates_items.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_certificates_items = relations(
  landing_page_certificates_items,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_certificates_items._parentID],
      references: [landing_page.id],
      relationName: 'certificates_items',
    }),
    _locales: many(landing_page_certificates_items_locales, {
      relationName: '_locales',
    }),
    image: one(media, {
      fields: [landing_page_certificates_items.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_landing_page_blocks_video_review_locales = relations(
  landing_page_blocks_video_review_locales,
  ({ one }) => ({
    _parentID: one(landing_page_blocks_video_review, {
      fields: [landing_page_blocks_video_review_locales._parentID],
      references: [landing_page_blocks_video_review.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_blocks_video_review = relations(
  landing_page_blocks_video_review,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_blocks_video_review._parentID],
      references: [landing_page.id],
      relationName: '_blocks_videoReview',
    }),
    _locales: many(landing_page_blocks_video_review_locales, {
      relationName: '_locales',
    }),
    video: one(media, {
      fields: [landing_page_blocks_video_review.video],
      references: [media.id],
      relationName: 'video',
    }),
    image: one(media, {
      fields: [landing_page_blocks_video_review.image],
      references: [media.id],
      relationName: 'image',
    }),
    avatar: one(media, {
      fields: [landing_page_blocks_video_review.avatar],
      references: [media.id],
      relationName: 'avatar',
    }),
  }),
)
export const relations_landing_page_blocks_text_review_locales = relations(
  landing_page_blocks_text_review_locales,
  ({ one }) => ({
    _parentID: one(landing_page_blocks_text_review, {
      fields: [landing_page_blocks_text_review_locales._parentID],
      references: [landing_page_blocks_text_review.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_blocks_text_review = relations(
  landing_page_blocks_text_review,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_blocks_text_review._parentID],
      references: [landing_page.id],
      relationName: '_blocks_textReview',
    }),
    _locales: many(landing_page_blocks_text_review_locales, {
      relationName: '_locales',
    }),
    avatar: one(media, {
      fields: [landing_page_blocks_text_review.avatar],
      references: [media.id],
      relationName: 'avatar',
    }),
  }),
)
export const relations_landing_page_reviews_video_items_locales = relations(
  landing_page_reviews_video_items_locales,
  ({ one }) => ({
    _parentID: one(landing_page_reviews_video_items, {
      fields: [landing_page_reviews_video_items_locales._parentID],
      references: [landing_page_reviews_video_items.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_reviews_video_items = relations(
  landing_page_reviews_video_items,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_reviews_video_items._parentID],
      references: [landing_page.id],
      relationName: 'reviews_videoItems',
    }),
    _locales: many(landing_page_reviews_video_items_locales, {
      relationName: '_locales',
    }),
    image: one(media, {
      fields: [landing_page_reviews_video_items.image],
      references: [media.id],
      relationName: 'image',
    }),
    avatar: one(media, {
      fields: [landing_page_reviews_video_items.avatar],
      references: [media.id],
      relationName: 'avatar',
    }),
  }),
)
export const relations_landing_page_reviews_text_items_locales = relations(
  landing_page_reviews_text_items_locales,
  ({ one }) => ({
    _parentID: one(landing_page_reviews_text_items, {
      fields: [landing_page_reviews_text_items_locales._parentID],
      references: [landing_page_reviews_text_items.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_reviews_text_items = relations(
  landing_page_reviews_text_items,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_reviews_text_items._parentID],
      references: [landing_page.id],
      relationName: 'reviews_textItems',
    }),
    _locales: many(landing_page_reviews_text_items_locales, {
      relationName: '_locales',
    }),
    avatar: one(media, {
      fields: [landing_page_reviews_text_items.avatar],
      references: [media.id],
      relationName: 'avatar',
    }),
  }),
)
export const relations_landing_page_footer_left_links_locales = relations(
  landing_page_footer_left_links_locales,
  ({ one }) => ({
    _parentID: one(landing_page_footer_left_links, {
      fields: [landing_page_footer_left_links_locales._parentID],
      references: [landing_page_footer_left_links.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_footer_left_links = relations(
  landing_page_footer_left_links,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_footer_left_links._parentID],
      references: [landing_page.id],
      relationName: 'footer_leftLinks',
    }),
    _locales: many(landing_page_footer_left_links_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_footer_right_links_locales = relations(
  landing_page_footer_right_links_locales,
  ({ one }) => ({
    _parentID: one(landing_page_footer_right_links, {
      fields: [landing_page_footer_right_links_locales._parentID],
      references: [landing_page_footer_right_links.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_footer_right_links = relations(
  landing_page_footer_right_links,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_footer_right_links._parentID],
      references: [landing_page.id],
      relationName: 'footer_rightLinks',
    }),
    _locales: many(landing_page_footer_right_links_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_footer_social_links_locales = relations(
  landing_page_footer_social_links_locales,
  ({ one }) => ({
    _parentID: one(landing_page_footer_social_links, {
      fields: [landing_page_footer_social_links_locales._parentID],
      references: [landing_page_footer_social_links.id],
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_footer_social_links = relations(
  landing_page_footer_social_links,
  ({ one, many }) => ({
    _parentID: one(landing_page, {
      fields: [landing_page_footer_social_links._parentID],
      references: [landing_page.id],
      relationName: 'footer_socialLinks',
    }),
    _locales: many(landing_page_footer_social_links_locales, {
      relationName: '_locales',
    }),
  }),
)
export const relations_landing_page_locales = relations(landing_page_locales, ({ one }) => ({
  _parentID: one(landing_page, {
    fields: [landing_page_locales._parentID],
    references: [landing_page.id],
    relationName: '_locales',
  }),
}))
export const relations_landing_page = relations(landing_page, ({ one, many }) => ({
  header_navItems: many(landing_page_header_nav_items, {
    relationName: 'header_navItems',
  }),
  hero_backgroundImage: one(media, {
    fields: [landing_page.hero_backgroundImage],
    references: [media.id],
    relationName: 'hero_backgroundImage',
  }),
  hero_figureImage: one(media, {
    fields: [landing_page.hero_figureImage],
    references: [media.id],
    relationName: 'hero_figureImage',
  }),
  project_image: one(media, {
    fields: [landing_page.project_image],
    references: [media.id],
    relationName: 'project_image',
  }),
  forWho_primaryItems: many(landing_page_for_who_primary_items, {
    relationName: 'forWho_primaryItems',
  }),
  forWho_secondaryItems: many(landing_page_for_who_secondary_items, {
    relationName: 'forWho_secondaryItems',
  }),
  results_backgroundImage: one(media, {
    fields: [landing_page.results_backgroundImage],
    references: [media.id],
    relationName: 'results_backgroundImage',
  }),
  results_image: one(media, {
    fields: [landing_page.results_image],
    references: [media.id],
    relationName: 'results_image',
  }),
  results_items: many(landing_page_results_items, {
    relationName: 'results_items',
  }),
  process_steps: many(landing_page_process_steps, {
    relationName: 'process_steps',
  }),
  program_modules: many(landing_page_program_modules, {
    relationName: 'program_modules',
  }),
  expertise_image: one(media, {
    fields: [landing_page.expertise_image],
    references: [media.id],
    relationName: 'expertise_image',
  }),
  expertise_stats: many(landing_page_expertise_stats, {
    relationName: 'expertise_stats',
  }),
  certificates_items: many(landing_page_certificates_items, {
    relationName: 'certificates_items',
  }),
  _blocks_videoReview: many(landing_page_blocks_video_review, {
    relationName: '_blocks_videoReview',
  }),
  _blocks_textReview: many(landing_page_blocks_text_review, {
    relationName: '_blocks_textReview',
  }),
  reviews_videoItems: many(landing_page_reviews_video_items, {
    relationName: 'reviews_videoItems',
  }),
  reviews_textItems: many(landing_page_reviews_text_items, {
    relationName: 'reviews_textItems',
  }),
  cta_backgroundImage: one(media, {
    fields: [landing_page.cta_backgroundImage],
    references: [media.id],
    relationName: 'cta_backgroundImage',
  }),
  contact_image: one(media, {
    fields: [landing_page.contact_image],
    references: [media.id],
    relationName: 'contact_image',
  }),
  footer_leftLinks: many(landing_page_footer_left_links, {
    relationName: 'footer_leftLinks',
  }),
  footer_rightLinks: many(landing_page_footer_right_links, {
    relationName: 'footer_rightLinks',
  }),
  footer_socialLinks: many(landing_page_footer_social_links, {
    relationName: 'footer_socialLinks',
  }),
  _locales: many(landing_page_locales, {
    relationName: '_locales',
  }),
}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_form_submissions_status: typeof enum_form_submissions_status
  enum_landing_page_expertise_stats_align: typeof enum_landing_page_expertise_stats_align
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  media_locales: typeof media_locales
  form_submissions: typeof form_submissions
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  landing_page_header_nav_items: typeof landing_page_header_nav_items
  landing_page_header_nav_items_locales: typeof landing_page_header_nav_items_locales
  landing_page_for_who_primary_items: typeof landing_page_for_who_primary_items
  landing_page_for_who_primary_items_locales: typeof landing_page_for_who_primary_items_locales
  landing_page_for_who_secondary_items: typeof landing_page_for_who_secondary_items
  landing_page_for_who_secondary_items_locales: typeof landing_page_for_who_secondary_items_locales
  landing_page_results_items: typeof landing_page_results_items
  landing_page_results_items_locales: typeof landing_page_results_items_locales
  landing_page_process_steps: typeof landing_page_process_steps
  landing_page_process_steps_locales: typeof landing_page_process_steps_locales
  landing_page_program_modules: typeof landing_page_program_modules
  landing_page_program_modules_locales: typeof landing_page_program_modules_locales
  landing_page_expertise_stats: typeof landing_page_expertise_stats
  landing_page_expertise_stats_locales: typeof landing_page_expertise_stats_locales
  landing_page_certificates_items: typeof landing_page_certificates_items
  landing_page_certificates_items_locales: typeof landing_page_certificates_items_locales
  landing_page_blocks_video_review: typeof landing_page_blocks_video_review
  landing_page_blocks_video_review_locales: typeof landing_page_blocks_video_review_locales
  landing_page_blocks_text_review: typeof landing_page_blocks_text_review
  landing_page_blocks_text_review_locales: typeof landing_page_blocks_text_review_locales
  landing_page_reviews_video_items: typeof landing_page_reviews_video_items
  landing_page_reviews_video_items_locales: typeof landing_page_reviews_video_items_locales
  landing_page_reviews_text_items: typeof landing_page_reviews_text_items
  landing_page_reviews_text_items_locales: typeof landing_page_reviews_text_items_locales
  landing_page_footer_left_links: typeof landing_page_footer_left_links
  landing_page_footer_left_links_locales: typeof landing_page_footer_left_links_locales
  landing_page_footer_right_links: typeof landing_page_footer_right_links
  landing_page_footer_right_links_locales: typeof landing_page_footer_right_links_locales
  landing_page_footer_social_links: typeof landing_page_footer_social_links
  landing_page_footer_social_links_locales: typeof landing_page_footer_social_links_locales
  landing_page: typeof landing_page
  landing_page_locales: typeof landing_page_locales
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media_locales: typeof relations_media_locales
  relations_media: typeof relations_media
  relations_form_submissions: typeof relations_form_submissions
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_landing_page_header_nav_items_locales: typeof relations_landing_page_header_nav_items_locales
  relations_landing_page_header_nav_items: typeof relations_landing_page_header_nav_items
  relations_landing_page_for_who_primary_items_locales: typeof relations_landing_page_for_who_primary_items_locales
  relations_landing_page_for_who_primary_items: typeof relations_landing_page_for_who_primary_items
  relations_landing_page_for_who_secondary_items_locales: typeof relations_landing_page_for_who_secondary_items_locales
  relations_landing_page_for_who_secondary_items: typeof relations_landing_page_for_who_secondary_items
  relations_landing_page_results_items_locales: typeof relations_landing_page_results_items_locales
  relations_landing_page_results_items: typeof relations_landing_page_results_items
  relations_landing_page_process_steps_locales: typeof relations_landing_page_process_steps_locales
  relations_landing_page_process_steps: typeof relations_landing_page_process_steps
  relations_landing_page_program_modules_locales: typeof relations_landing_page_program_modules_locales
  relations_landing_page_program_modules: typeof relations_landing_page_program_modules
  relations_landing_page_expertise_stats_locales: typeof relations_landing_page_expertise_stats_locales
  relations_landing_page_expertise_stats: typeof relations_landing_page_expertise_stats
  relations_landing_page_certificates_items_locales: typeof relations_landing_page_certificates_items_locales
  relations_landing_page_certificates_items: typeof relations_landing_page_certificates_items
  relations_landing_page_blocks_video_review_locales: typeof relations_landing_page_blocks_video_review_locales
  relations_landing_page_blocks_video_review: typeof relations_landing_page_blocks_video_review
  relations_landing_page_blocks_text_review_locales: typeof relations_landing_page_blocks_text_review_locales
  relations_landing_page_blocks_text_review: typeof relations_landing_page_blocks_text_review
  relations_landing_page_reviews_video_items_locales: typeof relations_landing_page_reviews_video_items_locales
  relations_landing_page_reviews_video_items: typeof relations_landing_page_reviews_video_items
  relations_landing_page_reviews_text_items_locales: typeof relations_landing_page_reviews_text_items_locales
  relations_landing_page_reviews_text_items: typeof relations_landing_page_reviews_text_items
  relations_landing_page_footer_left_links_locales: typeof relations_landing_page_footer_left_links_locales
  relations_landing_page_footer_left_links: typeof relations_landing_page_footer_left_links
  relations_landing_page_footer_right_links_locales: typeof relations_landing_page_footer_right_links_locales
  relations_landing_page_footer_right_links: typeof relations_landing_page_footer_right_links
  relations_landing_page_footer_social_links_locales: typeof relations_landing_page_footer_social_links_locales
  relations_landing_page_footer_social_links: typeof relations_landing_page_footer_social_links
  relations_landing_page_locales: typeof relations_landing_page_locales
  relations_landing_page: typeof relations_landing_page
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
