/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('uk' | 'en') | ('uk' | 'en')[];
  globals: {
    'landing-page': LandingPage;
  };
  globalsSelect: {
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
  };
  locale: 'uk' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  seedKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  message: string;
  status?: ('new' | 'in-progress' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  seedKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  seo: {
    metaTitle: string;
    metaDescription: string;
  };
  header: {
    logoText: string;
    ctaLabel: string;
    navItems?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  hero: {
    titleLineOne: string;
    titleLineTwo: string;
    script: string;
    subtitle: string;
    description: string;
    desktopDescription: string;
    availability: string;
    durationValue: string;
    durationLabel: string;
    backgroundImage: number | Media;
    figureImage: number | Media;
  };
  project: {
    title: string;
    scriptTitle: string;
    intro: string;
    body: string;
    ctaLabel: string;
    ctaHref: string;
    image: number | Media;
  };
  forWho: {
    title: string;
    scriptTitle: string;
    primaryItems?:
      | {
          icon: number | Media;
          label: string;
          id?: string | null;
        }[]
      | null;
    secondaryItems?:
      | {
          icon: number | Media;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  results: {
    title: string;
    summary: string;
    backgroundImage: number | Media;
    image: number | Media;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  process: {
    title: string;
    scriptTitle: string;
    steps?:
      | {
          title: string;
          description: string;
          raised?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  program: {
    title: string;
    modules?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  expertise: {
    title: string;
    scriptTitle: string;
    description: string;
    intro: string;
    image: number | Media;
    stats?:
      | {
          title: string;
          description: string;
          align: 'start' | 'end';
          id?: string | null;
        }[]
      | null;
  };
  certificates: {
    title: string;
    scriptWordOne: string;
    scriptWordTwo: string;
    items?:
      | {
          label: string;
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  reviews: {
    title: string;
    scriptTitle: string;
    /**
     * Натисни "Add" і вибери тип блоку: відео або текстовий відгук.
     */
    items?:
      | (
          | {
              /**
               * Завантаж реальне відео для відгуку. Підходять mp4 / mov / webm, і на фронті воно відкриється після кліку по картці.
               */
              video?: (number | null) | Media;
              image: number | Media;
              avatar: number | Media;
              name: string;
              /**
               * Необов'язково. Якщо URL заданий, іконка Instagram з'явиться в картці відгуку.
               */
              instagramUrl?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'videoReview';
            }
          | {
              text: string;
              avatar: number | Media;
              name: string;
              /**
               * Необов'язково. Якщо URL заданий, іконка Instagram з'явиться в картці відгуку.
               */
              instagramUrl?: string | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'textReview';
            }
        )[]
      | null;
    videoItems?:
      | {
          image: number | Media;
          avatar: number | Media;
          name: string;
          /**
           * Необов'язково. Якщо URL заданий, іконка Instagram з'явиться в картці відгуку.
           */
          instagramUrl?: string | null;
          id?: string | null;
        }[]
      | null;
    textItems?:
      | {
          text: string;
          avatar: number | Media;
          name: string;
          /**
           * Необов'язково. Якщо URL заданий, іконка Instagram з'явиться в картці відгуку.
           */
          instagramUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    title: string;
    description: string;
    buttonLabel: string;
    buttonHref: string;
    backgroundImage: number | Media;
  };
  contact: {
    eyebrow: string;
    title: string;
    script: string;
    image: number | Media;
    placeholders: {
      firstName: string;
      lastName: string;
      email: string;
      phone: string;
      message: string;
    };
    submitLabel: string;
    successMessage: string;
    errorMessage: string;
  };
  footer: {
    leftLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    rightLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    logoText: string;
    socialLinks?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    contact: {
      title: string;
      label: string;
      href: string;
    };
    write: {
      title: string;
      label: string;
      href: string;
    };
    socialsTitle: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  header?:
    | T
    | {
        logoText?: T;
        ctaLabel?: T;
        navItems?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  hero?:
    | T
    | {
        titleLineOne?: T;
        titleLineTwo?: T;
        script?: T;
        subtitle?: T;
        description?: T;
        desktopDescription?: T;
        availability?: T;
        durationValue?: T;
        durationLabel?: T;
        backgroundImage?: T;
        figureImage?: T;
      };
  project?:
    | T
    | {
        title?: T;
        scriptTitle?: T;
        intro?: T;
        body?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
      };
  forWho?:
    | T
    | {
        title?: T;
        scriptTitle?: T;
        primaryItems?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        secondaryItems?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
      };
  results?:
    | T
    | {
        title?: T;
        summary?: T;
        backgroundImage?: T;
        image?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        title?: T;
        scriptTitle?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              raised?: T;
              id?: T;
            };
      };
  program?:
    | T
    | {
        title?: T;
        modules?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  expertise?:
    | T
    | {
        title?: T;
        scriptTitle?: T;
        description?: T;
        intro?: T;
        image?: T;
        stats?:
          | T
          | {
              title?: T;
              description?: T;
              align?: T;
              id?: T;
            };
      };
  certificates?:
    | T
    | {
        title?: T;
        scriptWordOne?: T;
        scriptWordTwo?: T;
        items?:
          | T
          | {
              label?: T;
              image?: T;
              id?: T;
            };
      };
  reviews?:
    | T
    | {
        title?: T;
        scriptTitle?: T;
        items?:
          | T
          | {
              videoReview?:
                | T
                | {
                    video?: T;
                    image?: T;
                    avatar?: T;
                    name?: T;
                    instagramUrl?: T;
                    id?: T;
                    blockName?: T;
                  };
              textReview?:
                | T
                | {
                    text?: T;
                    avatar?: T;
                    name?: T;
                    instagramUrl?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        videoItems?:
          | T
          | {
              image?: T;
              avatar?: T;
              name?: T;
              instagramUrl?: T;
              id?: T;
            };
        textItems?:
          | T
          | {
              text?: T;
              avatar?: T;
              name?: T;
              instagramUrl?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        buttonLabel?: T;
        buttonHref?: T;
        backgroundImage?: T;
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        script?: T;
        image?: T;
        placeholders?:
          | T
          | {
              firstName?: T;
              lastName?: T;
              email?: T;
              phone?: T;
              message?: T;
            };
        submitLabel?: T;
        successMessage?: T;
        errorMessage?: T;
      };
  footer?:
    | T
    | {
        leftLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        rightLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        logoText?: T;
        socialLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              label?: T;
              href?: T;
            };
        write?:
          | T
          | {
              title?: T;
              label?: T;
              href?: T;
            };
        socialsTitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}